#!/usr/bin/env python3
"""
Script interattivo per configurare il canale errori Telegram.

Uso:
    python setup_error_channel.py

Cosa fa:
    1. Verifica che TELEGRAM_BOT_TOKEN sia configurato
    2. Guida l'utente nella creazione del canale
    3. Recupera automaticamente l'ID del canale
    4. Aggiorna il file .env
    5. Testa l'invio di un messaggio di prova
"""

import os
import sys
import json
import asyncio
import aiohttp
from pathlib import Path
from typing import Optional

# Colori per output
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
BLUE = "\033[94m"
RESET = "\033[0m"
BOLD = "\033[1m"


def print_step(step: int, total: int, message: str):
    """Stampa uno step formattato."""
    print(f"\n{BOLD}[{step}/{total}]{RESET} {message}")


def print_success(message: str):
    """Stampa un messaggio di successo."""
    print(f"{GREEN}✓{RESET} {message}")


def print_warning(message: str):
    """Stampa un avviso."""
    print(f"{YELLOW}⚠{RESET} {message}")


def print_error(message: str):
    """Stampa un errore."""
    print(f"{RED}✗{RESET} {message}")


def print_info(message: str):
    """Stampa informazioni."""
    print(f"{BLUE}ℹ{RESET} {message}")


def load_env_file(env_path: Path) -> dict:
    """Carica le variabili da un file .env."""
    env_vars = {}
    if env_path.exists():
        with open(env_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key] = value
    return env_vars


def save_env_file(env_path: Path, env_vars: dict):
    """Salva le variabili in un file .env."""
    with open(env_path, 'w', encoding='utf-8') as f:
        f.write("# Giorgio Backend Configuration\n")
        f.write("# Generated by setup_error_channel.py\n\n")
        
        # Ordine logico delle variabili
        priority_keys = [
            'TELEGRAM_BOT_TOKEN',
            'TELEGRAM_ERROR_CHANNEL_ID',
            'DATABASE_URL',
            'WHITELIST_TELEGRAM_IDS',
            'SECRET_KEY',
        ]
        
        written = set()
        for key in priority_keys:
            if key in env_vars:
                value = env_vars[key]
                comment = {
                    'TELEGRAM_BOT_TOKEN': 'Bot token for Telegram integration',
                    'TELEGRAM_ERROR_CHANNEL_ID': 'Channel ID for error notifications (format: -100xxxxxxxxxx)',
                    'DATABASE_URL': 'Database connection URL',
                    'WHITELIST_TELEGRAM_IDS': 'List of allowed Telegram user IDs',
                    'SECRET_KEY': 'Secret key for security',
                }.get(key, '')
                
                if comment:
                    f.write(f"# {comment}\n")
                f.write(f"{key}={value}\n\n")
                written.add(key)
        
        # Scrivi le rimanenti
        for key, value in env_vars.items():
            if key not in written:
                f.write(f"{key}={value}\n")


async def get_bot_info(bot_token: str) -> Optional[dict]:
    """Recupera le informazioni del bot da Telegram."""
    url = f"https://api.telegram.org/bot{bot_token}/getMe"
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(url) as response:
                if response.status == 200:
                    data = await response.json()
                    if data.get('ok'):
                        return data['result']
                return None
    except Exception as e:
        print_error(f"Errore connessione Telegram: {e}")
        return None


async def test_channel_access(bot_token: str, channel_id: str) -> bool:
    """Testa se il bot può accedere al canale."""
    url = f"https://api.telegram.org/bot{bot_token}/getChat"
    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(url, json={'chat_id': channel_id}) as response:
                if response.status == 200:
                    data = await response.json()
                    return data.get('ok', False)
                return False
    except Exception:
        return False


async def send_test_message(bot_token: str, channel_id: str) -> bool:
    """Invia un messaggio di test nel canale."""
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    message = "🧪 *Test Configurazione*\n\nIl canale errori è stato configurato correttamente!\n\nDa ora riceverai qui gli errori delle automazioni YAP."
    
    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(url, json={
                'chat_id': channel_id,
                'text': message,
                'parse_mode': 'Markdown'
            }) as response:
                return response.status == 200
    except Exception as e:
        print_error(f"Errore invio messaggio: {e}")
        return False


async def find_channel_by_title(bot_token: str, title_keyword: str) -> Optional[str]:
    """Cerca un canale tra gli aggiornamenti recenti del bot."""
    url = f"https://api.telegram.org/bot{bot_token}/getUpdates"
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(url) as response:
                if response.status == 200:
                    data = await response.json()
                    if data.get('ok') and data.get('result'):
                        for update in data['result']:
                            # Cerca nei messaggi del canale
                            if 'message' in update and 'chat' in update['message']:
                                chat = update['message']['chat']
                                if chat.get('type') in ['channel', 'supergroup']:
                                    chat_title = chat.get('title', '')
                                    if title_keyword.lower() in chat_title.lower():
                                        return str(chat['id'])
                            # Cerca nelle my_chat_member (quando il bot viene aggiunto)
                            if 'my_chat_member' in update:
                                chat = update['my_chat_member']['chat']
                                if chat.get('type') in ['channel', 'supergroup']:
                                    chat_title = chat.get('title', '')
                                    if title_keyword.lower() in chat_title.lower():
                                        return str(chat['id'])
                return None
    except Exception:
        return None


def get_input_with_default(prompt: str, default: Optional[str] = None) -> str:
    """Ottiene input utente con valore di default."""
    if default:
        full_prompt = f"{prompt} [{default}]: "
    else:
        full_prompt = f"{prompt}: "
    
    user_input = input(full_prompt).strip()
    return user_input if user_input else (default or "")


async def main():
    """Flow principale di configurazione."""
    print(f"\n{BOLD}{'='*60}{RESET}")
    print(f"{BOLD}  Configurazione Canale Errori Telegram - Giorgio{RESET}")
    print(f"{BOLD}{'='*60}{RESET}\n")
    
    env_path = Path(__file__).parent / '.env'
    env_vars = load_env_file(env_path)
    
    # Step 1: Verifica TELEGRAM_BOT_TOKEN
    print_step(1, 5, "Verifica configurazione bot Telegram")
    
    bot_token = env_vars.get('TELEGRAM_BOT_TOKEN', os.getenv('TELEGRAM_BOT_TOKEN', ''))
    
    if not bot_token or bot_token in ['your_token_here', 'your_dev_token_here']:
        print_error("TELEGRAM_BOT_TOKEN non configurato!")
        print_info("Devi prima configurare TELEGRAM_BOT_TOKEN nel file .env")
        print_info("Ottienilo da @BotFather su Telegram")
        
        bot_token = get_input_with_default("Inserisci il token del bot")
        if not bot_token:
            print_error("Token richiesto. Uscita.")
            return 1
        
        env_vars['TELEGRAM_BOT_TOKEN'] = bot_token
        save_env_file(env_path, env_vars)
        print_success(f"Token salvato in {env_path}")
    else:
        print_success("TELEGRAM_BOT_TOKEN trovato")
    
    # Verifica che il token sia valido
    print_info("Verifica validità token con Telegram...")
    bot_info = await get_bot_info(bot_token)
    
    if not bot_info:
        print_error("Token non valido o impossibile contattare Telegram")
        print_info("Verifica che il token sia corretto e che il bot esista")
        return 1
    
    bot_username = bot_info.get('username', 'Unknown')
    bot_name = bot_info.get('first_name', 'Unknown')
    print_success(f"Bot trovato: @{bot_username} ({bot_name})")
    
    # Step 2: Verifica/crea canale
    print_step(2, 5, "Configurazione canale errori")
    
    existing_channel = env_vars.get('TELEGRAM_ERROR_CHANNEL_ID', '')
    
    if existing_channel and existing_channel != '-1001234567890':
        print_info(f"Canale esistente trovato: {existing_channel}")
        
        # Testa se il canale è ancora valido
        print_info("Verifica accesso al canale...")
        if await test_channel_access(bot_token, existing_channel):
            print_success("Il bot ha accesso al canale!")
            
            choice = get_input_with_default("Vuoi usare questo canale? (s/n)", "s")
            if choice.lower() in ['s', 'si', 'yes', 'y']:
                channel_id = existing_channel
            else:
                channel_id = None
        else:
            print_warning("Il bot non può accedere al canale. Probabilmente non è stato aggiunto come amministratore.")
            channel_id = None
    else:
        channel_id = None
    
    if not channel_id:
        print_info("\nPer creare il canale errori:")
        print(f"  1. Apri Telegram (web o app)")
        print(f"  2. Clicca su 'Nuovo canale' o 'New Channel'")
        print(f"  3. Nome suggerito: {BOLD}Giorgio Errors{RESET}")
        print(f"  4. Descrizione: Canale per ricevere errori delle automazioni YAP")
        print(f"  5. Imposta come {BOLD}Canale Privato{RESET} (più sicuro)")
        print(f"  6. Aggiungi @{bot_username} come {BOLD}Amministratore{RESET}")
        print(f"     (Necessario per inviare messaggi e screenshot)")
        
        print("\nDopo aver creato il canale e aggiunto il bot:")
        
        # Prova a trovare il canale automaticamente
        print_info("Cerco canali recenti dove il bot è stato aggiunto...")
        found_channel = await find_channel_by_title(bot_token, "error")
        
        if found_channel:
            print_success(f"Trovato canale candidato: {found_channel}")
            choice = get_input_with_default("Vuoi usare questo canale? (s/n)", "s")
            if choice.lower() in ['s', 'si', 'yes', 'y']:
                channel_id = found_channel
        
        if not channel_id:
            # Chiedi all'utente di inserire l'ID manualmente
            print_info("\nPer ottenere l'ID del canale:")
            print("  1. Vai nel canale appena creato")
            print("  2. Invia un qualsiasi messaggio nel canale")
            print("  3. Vai su https://api.telegram.org/bot<TOKEN>/getUpdates")
            print("     (sostituisci <TOKEN> con il token del tuo bot)")
            print("  4. Cerca 'chat':{'id':-100...} - quel numero è l'ID")
            print()
            
            manual_id = get_input_with_default("Inserisci l'ID del canale (formato: -100xxxxxxxxxx)")
            
            if manual_id:
                # Normalizza l'ID
                if not manual_id.startswith('-'):
                    manual_id = f"-100{manual_id}"
                channel_id = manual_id
            else:
                print_error("ID canale richiesto. Uscita.")
                return 1
    
    # Step 3: Salva configurazione
    print_step(3, 5, "Salvataggio configurazione")
    
    env_vars['TELEGRAM_ERROR_CHANNEL_ID'] = channel_id
    save_env_file(env_path, env_vars)
    print_success(f"Configurazione salvata in {env_path}")
    
    # Step 4: Test connessione
    print_step(4, 5, "Test connessione al canale")
    
    print_info("Verifica che il bot possa inviare messaggi...")
    
    if await test_channel_access(bot_token, channel_id):
        print_success("Accesso al canale confermato!")
        
        choice = get_input_with_default("Vuoi inviare un messaggio di test? (s/n)", "s")
        if choice.lower() in ['s', 'si', 'yes', 'y']:
            if await send_test_message(bot_token, channel_id):
                print_success("Messaggio di test inviato! Controlla il canale Telegram.")
            else:
                print_warning("Impossibile inviare messaggio di test.")
                print_info("Il canale potrebbe essere configurato correttamente, ma verifica manualmente.")
    else:
        print_error("Il bot non può accedere al canale!")
        print_info("Possibili cause:")
        print("  - Il bot non è stato aggiunto al canale")
        print("  - Il bot è stato aggiunto ma non come amministratore")
        print("  - L'ID del canale è sbagliato")
        print()
        print_info("Soluzione:")
        print(f"  1. Vai nelle impostazioni del canale")
        print(f"  2. Amministratori > Aggiungi Amministratore")
        print(f"  3. Cerca @{bot_username}")
        print(f"  4. Conferma l'aggiunta")
        print()
        print_warning("Configurazione salvata, ma il test è fallito.")
        print_info("Riprova dopo aver corretto i permessi.")
    
    # Step 5: Riepilogo
    print_step(5, 5, "Riepilogo configurazione")
    
    print(f"\n{BOLD}Configurazione completata:{RESET}")
    print(f"  Bot: @{bot_username}")
    print(f"  Canale errori: {channel_id}")
    print(f"  File .env: {env_path.absolute()}")
    print()
    print_info("Da ora, quando i worker YAP falliscono:")
    print("  - Riceverai un messaggio su Telegram")
    print("  - Con i dettagli dell'errore")
    print("  - E uno screenshot se disponibile")
    print()
    print(f"{BOLD}Per testare manualmente:{RESET}")
    print(f"  1. Avvia il backend: python main.py")
    print(f"  2. Chiama: POST /yap/notify-error")
    print(f"     con payload: {{'error_message': 'Test'}}")
    print()
    
    return 0


if __name__ == "__main__":
    try:
        exit_code = asyncio.run(main())
        sys.exit(exit_code)
    except KeyboardInterrupt:
        print("\n\nOperazione annullata dall'utente.")
        sys.exit(1)
    except Exception as e:
        print_error(f"Errore imprevisto: {e}")
        sys.exit(1)
